id = "bit"
name = "Bit"
version = "0.1.0"
schema_version = 1
authors = ["Alec Thomas <alec@swapoff.org>"]
description = "Syntax support for the bit build language"
repository = "https://github.com/alecthomas/bit"

[grammars.bit]
repository = "file:///Users/alec/dev/bit"
rev = "3acbd1901dcffb44479c2d062c457ff8babde185"
path = "integrations/tree-sitter"
