// Code generated by "enumer -type=Enum -json -text"; DO NOT EDIT.

package golang

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EnumName = "EnumAEnumB"

var _EnumIndex = [...]uint8{0, 5, 10}

const _EnumLowerName = "enumaenumb"

func (i Enum) String() string {
	if i < 0 || i >= Enum(len(_EnumIndex)-1) {
		return fmt.Sprintf("Enum(%d)", i)
	}
	return _EnumName[_EnumIndex[i]:_EnumIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnumNoOp() {
	var x [1]struct{}
	_ = x[EnumA-(0)]
	_ = x[EnumB-(1)]
}

var _EnumValues = []Enum{EnumA, EnumB}

var _EnumNameToValueMap = map[string]Enum{
	_EnumName[0:5]:       EnumA,
	_EnumLowerName[0:5]:  EnumA,
	_EnumName[5:10]:      EnumB,
	_EnumLowerName[5:10]: EnumB,
}

var _EnumNames = []string{
	_EnumName[0:5],
	_EnumName[5:10],
}

// EnumString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnumString(s string) (Enum, error) {
	if val, ok := _EnumNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnumNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Enum values", s)
}

// EnumValues returns all values of the enum
func EnumValues() []Enum {
	return _EnumValues
}

// EnumStrings returns a slice of all String values of the enum
func EnumStrings() []string {
	strs := make([]string, len(_EnumNames))
	copy(strs, _EnumNames)
	return strs
}

// IsAEnum returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Enum) IsAEnum() bool {
	for _, v := range _EnumValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Enum
func (i Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Enum
func (i *Enum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Enum should be a string, got %s", data)
	}

	var err error
	*i, err = EnumString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Enum
func (i Enum) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Enum
func (i *Enum) UnmarshalText(text []byte) error {
	var err error
	*i, err = EnumString(string(text))
	return err
}
