package bit

import (
	"github.com/Duncaen/go-ninja"
)

type Analyser interface {
	// Patterns returns a set of regular expressions that, if matched against files, will trigger the Analyser.
	Patterns() []string
	// Setup returns a set of ninja rules that are required by any build config generated by the Analyser.
	Setup() []ninja.Node
	// Analyse is called with each file matching the regular expressions returned by [Patterns].
	Analyse(file string) ([]ninja.Node, error)
}
