// Code generated by "stringer -type=Override -linecomment"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverrideReplace-0]
	_ = x[OverridePrepend-1]
	_ = x[OverrideAppend-2]
	_ = x[OverrideDelete-3]
}

const _Override_name = "replaceprependappenddelete"

var _Override_index = [...]uint8{0, 7, 14, 20, 26}

func (i Override) String() string {
	if i < 0 || i >= Override(len(_Override_index)-1) {
		return "Override(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Override_name[_Override_index[i]:_Override_index[i+1]]
}
