#!/bin/bash
set -euo pipefail
basedir="$(dirname "$0")/.."
name="$(basename "$0")"
dest="${TMPDIR:-/tmp}/${name}"
mkdir -p "$dest"
(cd "${basedir}" && ./bin/go build -trimpath -ldflags="-s -w -buildid=" -o "$dest/${name}" "./cmd/${name}") && exec "$dest/${name}" "$@"
